### PR TITLE
support multiple redis targets

### PR DESCRIPTION
**Pull request by bs-github**
I've implemented support for feeding multiple redis targets.

Via specifying more than one (host, port) tuple as options when loading the event broker module into nagios, we can feed more than one reds now.
```
broker_module=/usr/local/lib/flapjackfeeder.o redis_host=127.0.0.1,redis_port=6381,redis_host=localhost,redis_port=6380
```
This will work with as many targets as you want. 
It will feed any reachable target and try to (re)connect to unreachable targets every 15 seconds (configurable via `redis_connect_retry_interval=15`).
The reconnect attempt has a timeout of 1.5 seconds, which is the only nagios blocking part of the code except from the LPUSH to redis that could be slow as well, but if that fails to be fast (1.5s timeout), the connection will be considered unreachable and reconnected.
Therefore watch out for lines like this in the nagios.log:
```
[1432570967] flapjackfeeder: redis connection has to be (re)established (redis host '127.0.0.1', redis port '6381').
[1432570967] flapjackfeeder: Connection error: 'Connection refused'. But I'll retry to connect regulary.
```

### CODE REVIEW

**Comment by jessereynolds** [comment]
Nice work!

What is the timeout behaviour in the previous version in the case where redis takes longer than 1.5 seconds to complete an LPUSH?

In particular, is that LPUSH retried or that event is dropped?

**Comment by bs-github** [comment]
Events will be dropped. 
The older versions act in the same way.

**Comment by jessereynolds** [comment]
@bs-github is this good to merge? I think it is?

**Comment by bs-github** [comment]
yep, merging

**Pull request merged**
